### ISSUE TITLE
Email and File Decryption bad URL

### ISSUE THREAD

**Issue by TopView** [trustcrypto/OnlyKey-App#107]
In the **OnlyKey app** (5.2.0 running under Linux) and under the **Tools tab**, when I click **Encrypt Files** or  **Decrypt Files** I get bad urls:  [https://apps.crp.to/encrypt-files.html](https://apps.crp.to/encrypt-files.html) and [https://apps.crp.to/decrypt-files.html](https://apps.crp.to/decrypt-files.html)

**Comment by onlykey** [comment]
@TopView The issue has been fixed. Thanks!
