### ISSUE TITLE
App does not work with settime in udev rule

### ISSUE THREAD

**Issue by dswd** [trustcrypto/OnlyKey-App#108]
When one adds the settime command to the udev rule as mentioned in the rules file the App hangs at "Please connect your OnlyKey". Maybe the settime command somehow consumes an event that the App is waiting for.

**Comment by onlykey** [comment]
@dswd that is for use with the OnlyKey command line app, if you don't have that installed it would not work.

**Comment by dswd** [comment]
I think you misunderstood me. The settime command works well, TOTP generates a code instead of NOTSET. My problem is that the GUI App no longer works with the settime in the udev rule.

**Comment by onlykey** [comment]
@dswd Oh OK, does restarting the app help or is it no matter what its stuck on "Please connect your OnlyKey"

**Comment by dswd** [comment]
Nope, restarting the App does not work. I somehow fixed it by adding a sleep 3 before the settime command. That kind of works.

**Comment by dswd** [comment]
After reading the sources of the App and the CLI, I think I understand the reason for this behavior. It seams that the OnlyKey communicates via messages that are pending until read by a client (app or CLI). I guess that the OnlyKey sends a certain message when connected and the App takes this message as "the onlykey is connected"-event. However the settime on the CLI reads the message before the App can (as it is triggered by udev the very instant the device is connected) so the App will never see this message and wait for it forever. Does this make any sense?

**Comment by xeor** [comment]
This is happening to me as well, tried running app from source from master branch, and the newest  5.3.1 from snap. I had this in my udev config

```
ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="60fc", ENV{ID_MM_DEVICE_IGNORE}="1"
ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="60fc", ENV{MTP_NO_PROBE}="1"

SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="60fc", MODE:="0600", OWNER:="xeor", RUN+="/usr/bin/onlykey-cli settime"
KERNEL=="ttyACM*", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="60fc", MODE:="0600", OWNER:="xeor", RUN+="/usr/bin/onlykey-cli settime"
```

but had to change it to

```
ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="60fc", ENV{ID_MM_DEVICE_IGNORE}="1"
ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="60fc", ENV{MTP_NO_PROBE}="1"

SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="60fc", MODE:="0600", OWNER:="xeor"
KERNEL=="ttyACM*", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="60fc", MODE:="0600", OWNER:="xeor"
```

only diff is the `RUN` command.

`RUN` used to work. No idea why it stopped working..

**Comment by onlykey** [comment]
@dswd Both the CLI settime and the desktop app sends the settime, its used to set time and also a check to see if OnlyKey is locked or unlocked. Setting a delay should work fine for the udev rule.

@xeor It sounds like your issue is more of that the RUN command in your udev rule isn't running is that correct?

**Comment by xeor** [comment]
@onlykey, no.. `/usr/bin/onlykey-cli settime` runs fine. The problem is, if the RUN statement is in udev, the app is stuck in `Please connect your OnlyKey`. Same problem as @dswd

**Comment by onlykey** [comment]
@xeor Does it work if you wait like @dswd mentioned as a workaround:

RUN+="sleep 5 ; /usr/bin/onlykey-cli settime"

**Comment by xeor** [comment]
> @xeor Does it work if you wait like @dswd mentioned as a workaround:
> 
> RUN+="sleep 5 ; /usr/bin/onlykey-cli settime"

Oh.. didnt see that comment. Will cheer it out

**Comment by xeor** [comment]
> @xeor Does it work if you wait like @dswd mentioned as a workaround:
> 
> RUN+="sleep 5 ; /usr/bin/onlykey-cli settime"

that worked :)
