### ISSUE TITLE
Setting "Auto-launch app on system login" does not work on Manjaro XFCE Linux

### ISSUE THREAD

**Issue by tafli** [trustcrypto/OnlyKey-App#111]
Despite of disabling the setting "Auto-launch app on system login" it still starts when logging into my system.

System:
* Manjaro Linux
* Desktop: XFCE
* OnlyKey App v5.2

After some research I found the binary called `nw` and could locate it in my application startup. However, disabling and / or enabling the setting does not have any effect.

**Comment by onlykey** [comment]
@tafli Yes, NW is the app. Did you try removing it from your application startup?

**Comment by tafli** [comment]
@onlykey Yes, removing it manually from the application startup worked for me. When I got time, I'll have a look at the code and try to fix it. Any hints on that or already a solution?
