### ISSUE TITLE
App becomes unusable after trying to set a password with € in it.

### ISSUE THREAD

**Issue by jaypikay** [trustcrypto/OnlyKey-App#112]
If entering a password which contains €, the password won't be saved to the OnlyKey.
The "OnlyKey Slot Xy Configuration" dialog does not auto-close after clicken "Set Slot". The buttons "Wipe Slot" and "Set Slot" stay deactivated until the application is restarted.

Password example which fails: Baz€

**Comment by onlykey** [comment]
The app and OnlyKey only supports ASCII characters
