### ISSUE TITLE
Plausible deniability profile not offered during initialisation.

### ISSUE THREAD

**Issue by millosolomillo** [trustcrypto/OnlyKey-App#113]
Hello,

Is it me or the Plausible deniability profile is not offered anymore during the initialisation of the key?

I loaded the Standard Edition v0.2-beta.8c with the Onlykey App v 5.2.0 in Windows 10 and this is what I see:

![image](https://user-images.githubusercontent.com/4713166/76154795-daec0e00-60e2-11ea-9396-c1c6eb8f5431.png)

**Comment by millosolomillo** [comment]
Actually I didn't read the option in the first screen that allows to perform advanced initialisation:
![image](https://user-images.githubusercontent.com/4713166/76155028-b003b900-60e6-11ea-8281-6222267479a1.png)

Sorry.

**Comment by onlykey** [comment]
@millosolomillo Guide here - https://docs.crp.to/pdguide.html
