### ISSUE TITLE
OnlyKey WebCrypt App - Native?

### ISSUE THREAD

**Issue by sorcer1122** [trustcrypto/OnlyKey-App#115]
Hi,

On this page - https://docs.crp.to/webcrypt.html - it says: " The web app can also be released as a native app that does not require a web browser if this is preferred" then there is a link to mobile support but nothing further about native web app.

Any idea how to compile webcrypt native app for android? 

Thanks

**Comment by onlykey** [comment]
Right now the way to do this is to use this - https://github.com/jiahaog/nativefier

We will publish a native app using this method after the next webcrypt release
