### ISSUE TITLE
Advanced Slot Configuration

### ISSUE THREAD

**Issue by LRitzdorf** [trustcrypto/OnlyKey-App#116]
Hello,

I am not (at least, not yet) an OnlyKey user, but I am quite interested in the product. While browsing the User Guide, it occurred to me that the given options in the OnlyKey App's Slot Configuration dialog could potentially be inadequate for proper functionality.

For example, what happens if a certain website is arranged so that one has to press <kbd>Tab</kbd> several times before the username field becomes active? The App provides an option to press <kbd>Tab</kbd> once before typing the username, but not multiple times.

Rather than adding a number box (or similar feature), which would make the UI even more complex, it might be worth considering a second, "Advanced" tab (or expandable area below the existing options) where an advanced user could input their own keypress sequence. Something like the Python `String.format()` method, as well as its "f-strings," come to mind here -- for example, something like `\t\t{name}\r{pass}\r\t{f2}\r` would be appropriate for a website where the user has to press <kbd>Tab</kbd> twice to get to the username field, type the username, hit <kbd>Enter</kbd>, type the password, hit <kbd>Enter</kbd> followed by <kbd>Tab</kbd> to get to the second-factor field, type the second factor code, and finally hit <kbd>Enter</kbd> to submit.

Admittedly, it would take a pretty badly-designed website to require this, but it would extend the OnlyKey's potential use even further.

**Comment by onlykey** [comment]
@LRitzdorf The UI is currently designed to handle the most common logins. If you have an uncommon setup like you described you can just use OnlyKey to enter the password, it doesn't have to be used for URL, Username, and password for each site. We have considered using some sort of scripting like you described but for simplicity we have not decided to implement this, if we did it would probably be an advanced option.

**Comment by LRitzdorf** [comment]
@onlykey Fair enough. Thank you for your response.
