### ISSUE TITLE
Bug: Leading space is trimmed from stored password

### ISSUE THREAD

**Issue by basnappl** [trustcrypto/OnlyKey-App#117]
Hello,

Hopefully this is the right place to report this. I have discovered a bug using:

OnlyKey App v5.2.0
Firmware: v0.2-beta.8c
OS: Ubuntu

On the "Slots" tab, when trying to set a password, if my password has a leading space (" "), it gets trimmed off when it is stored such that it is not typed after pressing the button.

I'll have a look at the source and see if I can figure out where it is going wrong.

**Comment by timetoseek** [comment]
That is a good catch!  Confirming this bug also applies when using OnlyKey on Windows 10 Enterprise, the leading space is deleted if part of the password, and also deleted is a space at the end of the password
