### ISSUE TITLE
ECC Private Key creation

### ISSUE THREAD

**Issue by wgordon17** [trustcrypto/OnlyKey-App#119]
Hi, I appreciate that the OnlyKey is able to support ECC private keys, however there's no guidance on generating these keys. I've generated an ed25519 ssh key pair, however the private key is significantly longer than 32 bytes.

**Comment by basnappl** [comment]
The private key looks like:
`AAAAC3NzaC1lZDI1NTE5AAAAIPPpj8qZCBHQt0nEb04UnzR/1EJgVX3kkDEDXmYwKrRZ`
Which has two parts, both base64 encoded.  The first is `AAAAC3NzaC1lZDI1NTE5AAAAI` which decodes to `\0\0\0\vssh-ed25519\0` and the remainder is your 32 byte private key in base64 (equal to `3cfa63f2a64204742dd2711bd38527cd1ff51098155f79240c40d7998c0aad16` in hex).

See: https://unix.stackexchange.com/questions/414448/why-do-portions-of-ssh-public-and-private-keys-overlap

**Comment by pcrama** [comment]
Based on https://unix.stackexchange.com/a/466234, I came up with this to extract the private key as hex, but do not really know how to test it with my OnlyKey:
```shell
grep -v 'KEY----'  ~/.ssh/id_ed25519 | \
     base64 --decode | \
     od --skip-bytes=0xa1 --read-bytes=32 --format=x1 | \
     sed -ne 's/[^ ]* //' -e 's/ //gp' | \
     tr -d '\n'
```

**Comment by onlykey** [comment]
You can use ed25519 keys with the GPG agent now - https://docs.crp.to/onlykey-agent.html

You would use the OnlyKey app to load OpenPGP ed25519 key, like that used with protonmail
