### ISSUE TITLE
Add ability to change the HMACSHA1 key to a custom value

### ISSUE THREAD

**Issue by twostring** [trustcrypto/OnlyKey-App#120]
It doesn't look like the OnlyKey App can change the HMACSHA1 key to a custom value. The thread on KeePassXC integration implies that it's possible to set a custom key. Can this be exposed in the OnlyKey App or otherwise documented?

https://github.com/keepassxreboot/keepassxc/issues/2064#issuecomment-472583006

**Comment by onlykey** [comment]
@twostring This feature will be available in next firmware release

**Comment by onlykey** [comment]
@twostring This feature is now supported https://docs.crp.to/upgradeguide.html
