### ISSUE TITLE
Firmware update fails

### ISSUE THREAD

**Issue by computersalat** [trustcrypto/OnlyKey-App#134]
Last message received: UNLOCKED BOOTLOADERv1
RECEIVED OKFWUPDATE
Error firmware file block too large

I ended up here after entering 10 times wrong pin that should actually reset the key to factory default.
Thank you guys ... looks like I have now a useless token.

**Comment by onlykey** [comment]
That error message indicates you are not loading the correct firmware file. Follow the upgrade guide to download and upgrade - https://docs.crp.to/upgradeguide.html
