### ISSUE TITLE
5.3.0 release available as snap?

### ISSUE THREAD

**Issue by Ian2020** [trustcrypto/OnlyKey-App#136]
Hi,

Will the 5.3.0 release be arriving on [snap](https://snapcraft.io/onlykey-app)?

Thanks

**Comment by onlykey** [comment]
@Ian2020 Yes, we plan to do this.

**Comment by xeor** [comment]
It wasnt clear in the `OnlyKey Release Announcement` mail and reading the installation guide that snap is still stuck at `5.2.0`. Do you have a time estimate? If it is far, maybe give a headsup to the non-debian people? :)

**Comment by rodgolpe** [comment]
@xeor Thank you for the feedback. We are a bit behind on the 5.3.x snap because we discovered an issue with the Linux version of the app. We should have another update in a few days.

**Comment by Ian2020** [comment]
If I may be cheeky and tag a further question onto this - will it be able to run under Wayland? It looks like nw.js now [supports it](https://github.com/nwjs/nw.js/issues/5705) if that was a blocker before. That would be icing on the cake.

**Comment by onlykey** [comment]
The snap has been released along with DEB for v5.3.1. To install:
$ snap install --beta --devmode onlykey-app

@Ian2020 Wayland is supported if the app is built using NW.js v0.50 - https://nwjs.io/blog/v0.50.0/
However, this breaks the 'Settings' menu in the app, unfortunately that is not working past NW.js v0.40.2 so there is not a plan to release that until both are working.

**Comment by Ian2020** [comment]
Thanks very much!
