### ISSUE TITLE
Instructions for using debsig-verify

### ISSUE THREAD

**Issue by jameshibbard** [trustcrypto/OnlyKey-App#141]
On the [releases page](https://github.com/trustcrypto/OnlyKey-App/releases/tag/v5.3.1), it is suggested to verify the signature of the deb package using `debsig-verify`.

Would it be possible to add a link to some instructions explaining how to do this?

I am familiar with using `gpg --verify <sig> <file>` but have no experience using debsig-verify and could find no helpful resources online.

**Comment by onlykey** [comment]
Sure there is a good article here - https://blog.packagecloud.io/eng/2014/10/28/howto-gpg-sign-verify-deb-packages-apt-repositories/

**Comment by jameshibbard** [comment]
Thnx. Would be nice to add that to the README or so.
Would you accept a PR that does that?

**Comment by onlykey** [comment]
@jameshibbard Sure that would be great

**Comment by haplo** [comment]
I have been trying to set up debsig-verify, got this policy to work (in `/etc/debsig/policies/9A9F520D44EA53D1/onlykey.pol`):

```
<?xml version="1.0"?>
<!DOCTYPE Policy SYSTEM "http://www.debian.org/debsig/1.0/policy.dtd">
<Policy xmlns="https://www.debian.org/debsig/1.0/">

  <Origin Name="test" id="9A9F520D44EA53D1" Description="OnlyKey"/>


  <Selection>
    <Required Type="origin" File="debsig.gpg" id="9A9F520D44EA53D1"/>
  </Selection>

   <Verification MinOptional="0">
    <Required Type="origin" File="debsig.gpg" id="9A9F520D44EA53D1"/>
   </Verification>
</Policy>
```

I also created the keyring and imported the public key as specified by [this article](https://blog.packagecloud.io/eng/2014/10/28/howto-gpg-sign-verify-deb-packages-apt-repositories/).

However debsig-verify fails:

```
$ debsig-verify -v -d OnlyKey_5.3.1_amd64.deb 
debsig: Starting verification for: OnlyKey_5.3.1_amd64.deb
debsig:         getSigKeyID: got 9A9F520D44EA53D1 for origin key
debsig: Using policy directory: /etc/debsig/policies/9A9F520D44EA53D1
debsig:   Parsing policy file: /etc/debsig/policies/9A9F520D44EA53D1/onlykey.pol
debsig:     parsePolicyFile: parsing '/etc/debsig/policies/9A9F520D44EA53D1/onlykey.pol'
debsig:     parsePolicyFile: completed
debsig:     Checking Selection group(s).
debsig:       Processing 'origin' key...
gpg: no valid OpenPGP data found.
gpg: processing message failed: Unknown system error
debsig: getKeyID subprocess returned error exit status 2
```

**Comment by jameshibbard** [comment]
I just had a look at the article posted above and it appears quite dated.
I had another search and came across this, which explains the process a little better.
I'll send you a PR mentioning that article instead.

**Comment by jameshibbard** [comment]
@haplo: FWIW, here's the process I followed:

- Download latest deb package from [here](https://github.com/trustcrypto/OnlyKey-App/releases/tag/v5.3.1)
- Download PGP public key from same page
- Obtain the key ID: `gpg --with-subkey-fingerprint CryptoTrust_LLC_pub.asc`
- Create the following folders:
  - `sudo mkdir /usr/share/debsig/keyrings/9A9F520D44EA53D1`
  - `sudo mkdir /etc/debsig/policies/9A9F520D44EA53D1`
- Import the CryptoTrust key into the new keyring and name it `debsig.pgp`
  - `sudo touch /usr/share/debsig/keyrings/9A9F520D44EA53D1/debsig.gpg`
  - `sudo gpg --no-default-keyring --keyring /usr/share/debsig/keyrings/9A9F520D44EA53D1/debsig.gpg --import CryptoTrust_LLC_pub.asc`
- Create a `debsig.pol` file in the folder `/etc/debsig/policies/2CBDEBD7B3B59588` with the following content:
  ```xml
  <?xml version="1.0"?>
  <!DOCTYPE Policy SYSTEM "https://www.debian.org/debsig/1.0/policy.dtd">
  <Policy xmlns="https://www.debian.org/debsig/1.0/">
    <Origin Name="CryptoTrust" id="9A9F520D44EA53D1" Description="OnlyKey App"/>
    <Selection>
      <Required Type="origin" File="debsig.gpg" id="9A9F520D44EA53D1"/>
    </Selection>
    <Verification MinOptional="0">
      <Required Type="origin" File="debsig.gpg" id="9A9F520D44EA53D1"/>
    </Verification>
  </Policy>
  ```
- Note Replace `<Policy xmlns="https://www.debian.org/debsig/1.0/">` according to the Signature Namespace that is detected by running `debsig-verify --version`

After this I could verify the package:

```bash
 ~/Desktop  debsig-verify -v OnlyKey_5.3.1_amd64.deb                                                                                               
debsig: Starting verification for: OnlyKey_5.3.1_amd64.deb
debsig: Using policy directory: /etc/debsig/policies/9A9F520D44EA53D1
debsig:   Parsing policy file: /etc/debsig/policies/9A9F520D44EA53D1/debsig.pol
debsig:     Checking Selection group(s).
debsig:       Processing 'origin' key...
debsig:     Selection group(s) passed, policy is usable.
debsig: Using policy file: /etc/debsig/policies/9A9F520D44EA53D1/debsig.pol
debsig:     Checking Verification group(s).
debsig:       Processing 'origin' key...
debsig:     Verification group(s) passed, deb is validated.
debsig: Verified package from 'OnlyKey App' (CryptoTrust)
```

HTH

**Comment by haplo** [comment]
Thank you for the detailed steps @jameshibbard. This is basically what I had done. I tried again step by step and no luck, same error I was getting before.

> Create a `debsig.pol` file in the folder `/etc/debsig/policies/2CBDEBD7B3B59588`

I assume you meant `/etc/debsig/policies/9A9F520D44EA53D1` there.

**Comment by jameshibbard** [comment]
Oops, yeah, that was what I meant. Sorry. Typo.

Shame you couldn't get it working. Which distro are you using?

**Comment by haplo** [comment]
> Which distro are you using?

Kubuntu 20.04.2. I think the problem might be gpg from what I see in the debug output (`debsig-verify -d`). If I can find the cause I will comment here again.

**Comment by munderwoods** [comment]
Can I ask you guys a simple question about this? I don't know a lot about how gpg works. I set this up successfully (thanks a bunch for that by the way) and I can verify the OnlyKey_5.3.1_amd64.deb package included in the repo just fine. However, if I try to verify my other packages they fail. Is there some more setup required for each individual package you wish to verify? Like, do I need to create a new xml file for each one in its own directory? That will take a while since I need to verify 200gb of packages... If this isn't the case, should I just be able to open any of these packages and see a .dsc file to know that they are signed? If debsig-verify did detect a signature, but it was invalid, I'd assume it would say that instead of just "Origin Signature check failed. This deb might not be signed". Anyway, any help is appreciated. Thanks a bunch.

**Comment by onlykey** [comment]
There are different ways of signing deb files and may are not signed at all. I do believe you have to create a new xml file for each deb you are verifying. Unfortunately, there is no convenient way to verify DEBs that I am aware of.

**Comment by jonathancross** [comment]
Thanks @jameshibbard !

The instructions worked for me.  Here are gpg signed results:
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

debsig-verify -v OnlyKey_5.3.6_amd64.deb
debsig: Starting verification for: OnlyKey_5.3.6_amd64.deb
debsig: Using policy directory: /etc/debsig/policies/9A9F520D44EA53D1
debsig:   Parsing policy file: /etc/debsig/policies/9A9F520D44EA53D1/debsig.pol
debsig:     Checking Selection group(s).
debsig:       Processing 'origin' key...
debsig:     Selection group(s) passed, policy is usable.
debsig: Using policy file: /etc/debsig/policies/9A9F520D44EA53D1/debsig.pol
debsig:     Checking Verification group(s).
debsig:       Processing 'origin' key...
debsig:     Verification group(s) passed, deb is validated.
debsig: Verified package from 'OnlyKey App' (CryptoTrust)
-----BEGIN PGP SIGNATURE-----

iQEzBAEBCgAdFiEEMsk361Pa9SImG35c2FeN+Op8zxsFAmOXvC0ACgkQ2FeN+Op8
zxvsGQgAmJk4h9oeG/Gsvre8+3uwcj5X3aK8qqvYf2okXIkHHHgWJAlMByC32jYs
2EYv+Pj2biQek5RiRuGTmHIC6zU3FU/0GLHGm5wfvz1SbL6u5pL1k7mXy4OH97QN
j+6ZsqA1aTk7R2aDjLP/cqhYnEpiweRC/ZbU4aUj/J2IR28jyH0Tcg2QG2m1Qnf7
QlFhz4vWf4oXiRIOF261/k+0wj+YI9ctcyAalT4Co0i6T8QSJpXmZs1/oKEID4W/
y8Rg3WQ5IY+xS3Uxo2meiBiZ/AoaEFDAXMRxinxXpjlQOvRsim3qJGlGU5F1kGa1
Pm/jeqUYa2APGJp9RuBXPWjKZdIq+w==
=K4t/
-----END PGP SIGNATURE-----
```

Note: [my gpg key](https://jonathancross.com/C0C076132FFA7695.asc) is part of the OpenPGP Web Of Trust "Strong Set".

@onlykey :  Verification with `debsig-verify` will frustrate most users and lead to a situation where they simply don't verify the software.  Most other packages simply create a gpg detached signature file so that users can verify simply with:  <nobr>`gpg --verify OnlyKey_5.3.6_amd64.deb.asc`</nobr>

Please consider  supplying a detached sig so that users don't need to install a new tool, search through issues to find these instructions, use configure the policy, etc. -- Thanks!

**Comment by jameshibbard** [comment]
> Verification with debsig-verify will frustrate most users and lead to a situation where they simply don't verify the software. 

I agree with this and would also like to add my voice in asking for a detached sig file.

**Comment by onlykey** [comment]
@jameshibbard I will make a note to do this with the next release. Unfortunately, there isn't an easy self contained way to sign DEB files like there is with EXE or DMG.

**Comment by jameshibbard** [comment]
That would be awesome and very much appreciated :smiley: 
Keep up the good work!

**Comment by jonathancross** [comment]
> @jameshibbard I will make a note to do this with the next release. Unfortunately, there isn't an easy self contained way to sign DEB files like there is with EXE or DMG.

I see that you are already providing SHA256 fingerprints of the binaries in your release notes.
If you simply `gpg --clearsign` those, then we are good to go.
Maybe that is better for your workflow?

(unsigned SHA256 fingerprints are of limited value anyway)
