### ISSUE TITLE
Enter/Return is not typed with certain lengths of passwords.

### ISSUE THREAD

**Issue by schlomie** [trustcrypto/OnlyKey-App#142]
Within the OnlyKey configuration app, the Password field is noted to allow up to 56 characters.  This is correct - it does type out a password 56 characters long, and types an `<Enter>` at the end - if requested.

What is interesting however, passwords with lengths of 54 or 55 characters do not insert the `<Enter>` when requested.  A password of length 53 appears to function correctly.

Details:
Firmware: v2.1.0-prodc
App: v5.3.1

**Comment by jaroszke** [comment]
@schlomie  
Trying to recreate the issue but setting a password to 54 or 55 characters and selecting "Return after Password" is performing a return after the password is typed. 
![image](https://user-images.githubusercontent.com/9595840/112922705-ee498d00-90da-11eb-922b-ce785b7c0224.png)

Do you have other values set in the slot?

**Comment by rodgolpe** [comment]
I can't reproduce this either. Set 2 different slots (an "A" and a "B") with 54 or 55 char passwords. Tried various combinations of updating the slots: password only, "Return after Password / None" setting only, changing both, changing to new vs. same password, etc. OK always respects my settings.
