### ISSUE TITLE
App should provide udev rules

### ISSUE THREAD

**Issue by niko-lay** [trustcrypto/OnlyKey-App#144]
I just installed onlykey app from .deb package and it not working, if freezes with message "Working...
Please wait "
Only after adding `49-onlykey.rules` from https://raw.githubusercontent.com/trustcrypto/trustcrypto.github.io/master/49-onlykey.rules app starts working normal.

Onlykey app version:
App v5.3.1
OnlyKey v0.2-beta.8c

Deb package don't have any `.rules`  files inside:
```
$ dpkg --listfiles  onlykey | grep rules
/opt/OnlyKey/node_modules/ajv/lib/compile/rules.js
/opt/OnlyKey/node_modules/psl/data/rules.json
$ dpkg --listfiles  onlykey | grep /etc
/opt/OnlyKey/node_modules/dashdash/etc
/opt/OnlyKey/node_modules/dashdash/etc/dashdash.bash_completion.in
```

my OS is:
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

```

**Comment by onlykey** [comment]
@niko-lay Yes that is the correct, the instructions for installing on Linux are here - https://docs.crp.to/linux.html

**Comment by niko-lay** [comment]
@onlykey I've added PR which add udev rules into .deb package, please review
