### ISSUE TITLE
Yubikey OATH-HOTP 

### ISSUE THREAD

**Issue by user908348** [trustcrypto/OnlyKey-App#147]
The authenticator for our [VPN software](https://kb.fortinet.com/kb/documentLink.do?externalID=FD45727) only supports their own hardware key or Yubikey OATH-HOTP

I see onlykey supports Yubikey HOTP but does it also support OATH-HOTP?
I installed the Yubikey software but it says Yubikey not detected and I can't export the CSV file required it seems.

**Comment by onlykey** [comment]
OnlyKey supports Yubico OTP which is not the same as HOTP. OnlyKey does not support HOTP only TOTP. HOTP is not widely used as TOTP has many advantages. It looks like at your link Fortinet does support TOTP. You would go as if you were going to add a mobile fortinet token, when the QR code is displayed there should be an option for can't scan or view key. You could then import that to OnlyKey and it would generate your TOTP - https://docs.crp.to/usersguide.html#google-authenticator-totp

If this works for you let me know

**Comment by user908348** [comment]
Thanks, useful information, I'll check with the supplier.
