### ISSUE TITLE
Wrong key usage when verifying a signature generated by the WebCrypt

### ISSUE THREAD

**Issue by dingwen07** [trustcrypto/OnlyKey-App#148]
When I signed a message on the WebCrypt, the wrong key was used for signing. The PGP program returned:
```
gpg: Signature made 2021/1/30 4:25:22
gpg:                using RSA key F823AE471F8F02AC
gpg: bad data signature from key F823AE471F8F02AC: Wrong key usage (0x00, 0x8)
gpg: Can't check signature: Wrong key usage
```

My key consists of three sub-keys. In addition to the primary key (used for signing), there are two sub-keys for Encryption and Authentication. Here are the details:
```
sec  rsa4096/C90F5D94EAB69014
     created: 2018-12-25  expires: never       usage: SC
     card-no: 0005 00008125
     trust: ultimate      validity: ultimate
ssb  rsa4096/4161795A39BE1A75
     created: 2018-12-25  expires: never       usage: E
     card-no: 0005 00008125
ssb  rsa4096/F823AE471F8F02AC
     created: 2018-12-25  expires: never       usage: A
     card-no: 0005 00008125
```
I tried various ways to import the key, including Auto Load; import the master key and set as signing key, and import Sub Key 1/2, and set as decryption key. Almost all import combinations have been tried, but still errors. The WebCrypt always uses my Authentication Key for signing, even when I have not imported it

My key can be imported into Mailvelope, so this is not a compatibility issue. Since I tried all the combinations when importing the key, I believe this should be a problem with the Desktop App.

**Comment by onlykey** [comment]
Only OpenPGP keys are supported, you can get GPG keys to work the documentation for that is here - https://docs.crp.to/importpgp.html#loading-keys-a

The signing key has to be set to slot 1 and the decryption key to slot 2

**Comment by dingwen07** [comment]
> Only OpenPGP keys are supported, you can get GPG keys to work the documentation for that is here - https://docs.crp.to/importpgp.html#loading-keys-a
> 
> 
> 
> The signing key has to be set to slot 1 and the decryption key to slot 2

As stated in the document, I imported the Signing Key (primary key) as Slot 1 and checked the relevant settings. Imported the Decryption Key (sub key 1) into Slot 2 and checked the relevant settings.  But still, the Authentication key (sub key 2) was actually used for signing.

**Comment by dingwen07** [comment]
I found the exact reason. If the public key provided to WebCrypt contains an Authentication subkey, WebCrypt will try to use it for signing instead of the master key/signature subkey. The reason why the Authentication subkey is displayed in verification error messages even though it is not loaded into OnlyKey is unclear, but this is undoubtedly a WebCrypt problem.

**Comment by onlykey** [comment]
@dingwen07 This is one of the reasons we only support standard OpenPGP keys, we recommend following this guide to creating keys for most users - https://docs.crp.to/importpgp.html

There are too many possible variations and options to fully support GPG keys and trying to do so would likely complicate things to where the average user would not use this. If you need GPG signing I would recommend using OnlyKey Agent with stored keys - https://docs.crp.to/onlykey-agent.html#gpg-agent-quickstart-guide-stored-keys
