### ISSUE TITLE
Bad encrypt/decrypt URLs 

### ISSUE THREAD

**Issue by Mongki** [trustcrypto/OnlyKey-App#149]
In the Windows app (5.3.0) the links to encrypt/decrypt messages/files under the "Tools" tab all direct to bad URLs

e.g.
"https://apps.crp.to/encrypt.html" instead of "https://apps.crp.to/app/encrypt"
"https://apps.crp.to/encrypt-files.html" instead of "https://apps.crp.to/app/encrypt-file"
And so on...

Appears to be the same as this issue #107

**Comment by timetoseek** [comment]
Confirmed, I get the same error message... running App v5.3.0 on Windows

**Comment by onlykey** [comment]
fixed in 5.3.2
