### ISSUE TITLE
Feature request: Allow addition of {macros} or 'arrow up/arrow down' keyboard codes to be configured before TOTP when editing entries

### ISSUE THREAD

**Issue by nkichukov** [trustcrypto/OnlyKey-App#150]
Hi folks,
I am running onlykey app version 5.3.1 here and I have a case, where after typing username and password, before proceeding to the TOTP key the web page login UI presents a drop-down list of options. Unfortunately, in my case it is the second option, so in the case of keepassxc, it allows me to define a {DOWN} macro, which sends the keyboard arrow down command before it proceeds to TOTP. So in the case of keepassxc it becomes:
{USERNAME}{TAB}{PASSWORD}{TAB}{DOWN}{TAB}{ENTER}

Can we have something similar added to the app and perhaps also the CLI app later on? I appreciate having the tabs and enters options in the UI, but in this case this is not enough.

It does not have to be for the arrow keys only, capturing user input would be ideal, or perhaps defining some macros the way keepassxc autotype has it?

Thanks!

**Comment by onlykey** [comment]
@nkichukov You should be able to do down arrow with sysadmin mode https://docs.crp.to/usersguide.html#sysadmin-mode

**Comment by nkichukov** [comment]
Thanks Tim,
took me a while to discover where to put what and a few trials and errors(had test cases where the OK would type 815 new lines or tabs in a roll) before I got an actual working configuration.
This can be closed.
Thank you.
