### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by loigu** [trustcrypto/OnlyKey-App#156]
It would be great to have support for the app functionality available on android too. I am often without computer and then...
How to check which slot is assigned to what? 
How to add/change passwords?
(these two Features are most missi g by me on android...)

**Comment by onlykey** [comment]
You can use the on the go feature to type out slot labels into a text editor on Android by holding down button #2 for 5+ seconds. Unfortunately there is not an app to modify passwords, it would be possible to use the onlykey-cli on Android but we have not tested this.

**Comment by loigu** [comment]
I tried to compile the cli under termux, no success (missing dependencies). 

Cli is not very user-friendly way,, but sufficient for me. If there would be a build (apk) available...

**Comment by onlykey** [comment]
Hi, unfortunately we have no plans to develop and Android or iOS app at this time. The reason being the app would have to be built from scratch and we do not have a developer that specializes in this. The desktop app is cross-platform for Windows, Mac, Linux, and Chrome OS.

**Comment by onlykey** [comment]
@ipfreer Yes you can use TOTP on Android and iOS, this describes how to do that - 
https://docs.onlykey.io/usersguide.html#google-authenticator-otg
https://docs.onlykey.io/mobile.html#androidios-static-password-totp-and-yubikey-otp-support
