### ISSUE TITLE
Memory usage on Windows

### ISSUE THREAD

**Issue by mpmc** [trustcrypto/OnlyKey-App#157]
Not 100% sure where to post this but I suppose this repo makes the most sense. There appears to be a leak in the app or one of its components. I think in this case, node webkit.
![mem](https://user-images.githubusercontent.com/2352508/119500395-47d6dc80-bd57-11eb-9f57-b74f469358ce.png)

I'm not even sure why it was running in the background as I closed the app last night (at least 12 hours prior), and went to bed!

Now I know this isn't exactly the best bug report as it contains very little information. However I thought I would post it so there is a record of it.

**Comment by onlykey** [comment]
Yes, the OnlyKey uses nwjs - https://nwjs.io/

NWJS uses Chromium to create cross-platform apps

**Comment by mpmc** [comment]
> Yes, the OnlyKey uses nwjs - https://nwjs.io/
> 
> NWJS uses Chromium to create cross-platform apps
> 
> Can you verify your OnlyKey app version?

5.3.0

HTH

**Comment by onlykey** [comment]
Thanks for verifying. We do have a new version here would you be able to try that and see if you run into the issue again?

https://github.com/trustcrypto/OnlyKey-App/releases/tag/v5.3.2
