### ISSUE TITLE
Change timestamp format of backup filenames

### ISSUE THREAD

**Issue by Ian2020** [trustcrypto/OnlyKey-App#158]
This is pretty minor feature request but the backup process on my system writes files with a default filename that includes a timestamp like this:

```text
onlykey-backup-MM-D-YYYY-H-M-[AM/PM].txt
```

This timestamp causes a strange ordering when files in a dir are listed in name order as the month and date come first. Please could the default timestamp be in reverse magnitude, i.e. something like:

```text
onlykey-backup-YYYY-MM-DD-HH-MM-[AM/PM].txt
```

So year-month-day order which will see files always ordered correctly by file managers. Further please could the day, month, hour and minute always be at least 2 digits with leading zeros where needed. Thanks!

**Comment by rodgolpe** [comment]
fixed in https://github.com/trustcrypto/OnlyKey-App/pull/192
