### ISSUE TITLE
No deb package on v5.3.2

### ISSUE THREAD

**Issue by TheSirC** [trustcrypto/OnlyKey-App#161]
Hi !

As far as I can see in the [5.3.2 release](https://github.com/trustcrypto/OnlyKey-App/releases/tag/v5.3.2), no deb package was provided / built even if the release note specify 

> Linux
> OnlyKey_5.3.2_amd64.deb
> GPG Signature verify with debsig-verify

Am I missing something ? Could it be possible to provide that deb package ? 

Thanking you in advance,

**Comment by onlykey** [comment]
There is now a deb in the 5.3.3 release
