### ISSUE TITLE
Snap flagged as proprietary in stores

### ISSUE THREAD

**Issue by issu-shooter** [trustcrypto/OnlyKey-App#164]
On snapcraft.io site, the license is unset, but in OS-specific stores like Gnome Software or Plasma Discover, they will be flagged as proprietary. This may lead to misunderstandings and confusions.

I read the license on github, and feel like it's similar to Mozilla Public License (MPL), maybe check this out. A common license can make onlykey more popular, please consider.

**Comment by onlykey** [comment]
@issu-shooter The license has been set to Apache-2.0. 
![image](https://user-images.githubusercontent.com/18121756/121435579-21b35e00-c94d-11eb-9184-b405ab83b62d.png)
