### ISSUE TITLE
Cannot change primary PIN

### ISSUE THREAD

**Issue by gasull** [trustcrypto/OnlyKey-App#167]
I cannot change the PIN after setting it.

In the OnlyKey app, I go to the Setup tab, click on "Change Primary PIN" button, check "I understand and accept the above risk", and then enter a new PIN in the OnlyKey keypad and click the "Next" button, but nothing happens.  If I ignore this and the new PIN a second time, again nothing happens after clicking "Next".

After removing the OnlyKey and inserting it again, I still need to enter the old PIN.

Versions of the app and the firmware:

App v5.3.3
OnlyKey v2.1.1-prodc

**Comment by onlykey** [comment]
Did you place device in config mode?
![image](https://user-images.githubusercontent.com/18121756/122574785-09fb6a00-d01e-11eb-8d43-c323c28b3122.png)

**Comment by gasull** [comment]
I was able to do it now, after trying many times.  I actually did it twice, but both times I had to try many times before it worked.

It seems to be very sensitive to the sequence of events:

 - assigning the OnlyKey device to the Qubes OS VM where I have the OnlyKey app installed
 - start OnlyKey app
 - go to Setup
 - place OnlyKey in config mode
 - click on Change Primary PIN
 - click on checkbox
 - enter new PIN
 - click Next
 - reenter new PIN
 - click Next

I'm not sure if I wrote the sequence in the right order.  I believe the setting the OnlyKey in config mode before or after some events above will mess up the process.
