### ISSUE TITLE
Why is this app sending hundreds of requests to accounts.google and s3.amazonaws.com?

### ISSUE THREAD

**Issue by IzumiSagiri** [trustcrypto/OnlyKey-App#176]
Step 1: Install a Linux firewall such as OpenSnitch.
Step 2: Launch this app.

Then you find that this app immediately sends about a hundred requests to accounts.google.com and s3.amazonaws.com and www.gstatic.com.

Please explain why this is happening, and can we have a fully offline version???

**Comment by rodgolpe** [comment]
Um, this doesn't sound right at all. The only one that makes sense to me is S3 -- of you've selected the option to check for app updates, it needs to pull a manifest.json that we host in an S3 bucket. We also use a web font that should be bundled. I'll investigate further.

**Comment by onlykey** [comment]
Chromium (NW.js) which the app is built on does call accounts.google.com, this should be fixed in a later version of Chromium

**Comment by onlykey** [comment]
@rodgolpe I tried the latest app (yet to be released 5.3.4) no calls to accounts.google.com. Can you verify? I used Lulu on Mac
```
brew install lulu
```

**Comment by rodgolpe** [comment]
Testing the latest app release 5.3.4 shows only 2 remote requests, which can both be disabled from the preferences menu:
- Automatically check for app updates
- Automatically check for firmware updates

![image](https://user-images.githubusercontent.com/601129/150921403-c8b210d3-0ff9-425f-b2c9-6fe4cf2b097c.png)
