### ISSUE TITLE
Linux: Autostart setting not respected

### ISSUE THREAD

**Issue by LRitzdorf** [trustcrypto/OnlyKey-App#183]
This issue resembles issues #89 and #90, except that those are exclusive to Windows. This issue pertains to the autostart function not respecting its current setting on Linux (app v5.3.3, latest as of this writing).

Whenever the OnlyKey desktop app is started, it creates an autostart file at `$XDG_CONFIG_HOME/autostart/nw.desktop`, regardless of the app's autostart setting. However, toggling the setting on and off does delete the autostart file properly.

**Comment by rodgolpe** [comment]
@LRitzdorf this issue has been resolved in PR #184 which is part of the latest release, https://github.com/trustcrypto/OnlyKey-App/releases/tag/v5.3.4.

**Comment by LRitzdorf** [comment]
Can confirm that this now works properly. For any future users looking for the old Settings menu, it's now accessible by right-clicking the system tray icon that appears when the app is active.

Quick note, though -- the Snap Store version of the app is now out of date. It's still on v5.3.3.

**Comment by LRitzdorf** [comment]
Quick note for anyone who comes across this later -- with Snap, upgrading the OnlyKey app requires the `--beta` flag, just like the initial install command. Otherwise, Snap won't find the new version.
