### ISSUE TITLE
Recent App and Firmware releases - safe to use or not?

### ISSUE THREAD

**Issue by grivanov** [trustcrypto/OnlyKey-App#185]
Noticed you recently released new OnlyKey App (5.3.4) and OnlyKey Firmware (2.1.2). However, they're tagged as "Pre-release". Will there be an "actual release" and if not, are those pre-releases safe to use on user devices?

**Comment by onlykey** [comment]
They are safe to use but the documentation is still for the previous release so some features would not be documented. Once the documentation is fully updated the pre-release tag will be removed.
