### ISSUE TITLE
Webcrypt on IOS safari not working after ios 15

### ISSUE THREAD

**Issue by scottroot** [trustcrypto/OnlyKey-App#186]
My onlykey had been working with OTG adapter to get time from webcrypt in Safari browser on my Iphone when it was IOS 14.xx.  I recently updated to IOS 15 and the page just says onlykey not connected.

Is there still any way to use OnlyKey on IOS for OTP 2FA?  Without the webcrypt page working I can't set the correct time so OTP only outputs "NOTSET".

The terminal apps I tried don't have necessary access to set the time.

**Comment by scottroot** [comment]
![image](https://user-images.githubusercontent.com/55364794/150668888-7a2b9993-15b7-4c92-9597-02d3c4a884df.png)
Just noticed it doesn't work on Chrome on my laptop anymore for encrypting either.  

Using updated versions of Onlykey: App v5.3.4, OnlyKey v2.1.2-prodc

**Comment by onlykey** [comment]
We have tested webcrypt on iOS 15 and have not heard reports of anyone else having issues. You just have to click the green button "Set time for OTP 2FA Authentication", OnlyKey flashes yellow then you proceed to use OTP
