### ISSUE TITLE
OnlyKey Duo not recognized?

### ISSUE THREAD

**Issue by dhammel** [trustcrypto/OnlyKey-App#194]
Hello,

I run linux Kubuntu 21.10, OnlyKey App self-compiled version 5.3.5 (I have tried the official released binary as well). I do have the udev rule setup, from running the original onlykey color version which still works with the app. The deb is manually extracted to an app directory of mine in ~/, rather than installed through dpkg.

When the duo is plugged in, either through the type c or a (Solid green light), it just says Please connect your OnlyKey. Plugging the Original OnlyKey Color in, and it works. I have tried 2 usb a ports, and the type c port of my laptop.

When I run the lsusb command, I do see an entry: 
Bus 001 Device 008: ID 1d50:60fc OpenMoko, Inc. OnlyKey Two-factor Authentication and Password Solution

In case It matters, i'd like to mention that at any given time only 1 onlykey device was ever plugged in at the same time.

so onlykey is being recognized by computer, know why the app isn't recognizing it?

Thank you

**Comment by onlykey** [comment]
Does you OnlyKey DUO light up? Does lsusb show this for OnlyKey or OnlyKey DUO?
> Bus 001 Device 008: ID 1d50:60fc OpenMoko, Inc. OnlyKey Two-factor Authentication and Password Solution

**Comment by dhammel** [comment]
@onlykey Any update on this?

**Comment by AndreOnCrypto** [comment]
I have the same issue on a Mac, managed to setup a PIN but the whole app UI assumes it's a normal OnlyKey and I can't figure out how to enter config mode to wipe the DUO.

**Comment by dhammel** [comment]
@AndreOnCrypto Its not the same issued if you managed to set a pin, I can't get that far. For me, it just says please connect your onlykey, as if It can't recognize the duo.

**Comment by onlykey** [comment]
@AndreOnCrypto It sounds like you are using an old version of the OnlyKey App. You need to follow instructions here to set up OnlyKey DUO https://docs.crp.to/duousersguide.html

**Comment by onlykey** [comment]
@dhammel 
>  I run linux Kubuntu 21.10, OnlyKey App self-compiled version 5.3.5 (I have tried the official released binary as well). I do have the udev rule setup, from running the original onlykey color version which still works with the app. The deb is manually extracted to an app directory of mine in ~/, rather than installed through dpkg.

Are you able to use the OnlyKey App install instructions from DEB file here - https://docs.crp.to/duousersguide.html#app-desktop
If this still does not work it is likely that you either have an OnlyKey DUO with hardware issues or there is something on the Linux system USB that is not working (May be UDEV rule). An easy way to determine which one it is would be to try your OnlyKey DUO on a Windows or Mac (Not a VM as UDEV/USB issue may be passed to VM)

> Tried pressing buttons on onlykey and managed to get it to turn yellow and once blue, though I'm not sure yet what those colors are for.

This is switching through the profiles - https://docs.crp.to/features.html#button-definitions

**Comment by dhammel** [comment]
@onlykey 

I tested onlykey duo on my grandfathers laptop running windows 10, and it does work. I have not set it up though, as I won’t be able to further configure it on my pc. So I have to figure out why this issue occurs on just my computer.
