### ISSUE TITLE
Onlykey Duo not getting Time when OnlyKey App is Running

### ISSUE THREAD

**Issue by no-sauce** [trustcrypto/OnlyKey-App#196]
I have an Onlykey Duo and I have it plugged into a windows 10 pc and I am unable to get the time while running the Onlykey App.  If I have a TOTP setup in a slot it types out 'NOTSET'.   I have tried running the app with administrator privilege's also with no success.  I have these checked in the app:

Auto-launch app on system login checked 
Automatically check for app updates checked 
Automatically check for firmware updates checked

running this firmware and onlykey version:
Firmware 3.0.0-prodp
OnlyKey App 5.3.5

My current workaround is running https://apps.crp.to/ which then gets the time and types out the TOTP correctly.

**Comment by onlykey** [comment]
@no-sauce Please try the latest app release here https://github.com/trustcrypto/OnlyKey-App/releases/tag/v5.3.6

**Comment by no-sauce** [comment]
Thanks, V5.3.6 fixed the problem
