### ISSUE TITLE
Onlykey No Admin No Administrator

### ISSUE THREAD

**Issue by freeload101** [trustcrypto/OnlyKey-App#200]
Because you can't install Onlykey without local admin ... not even set __COMPAT_LAYER=RUNASINVOKER  works ...

https://github.com/freeload101/SCRIPTS/blob/master/Windows_Batch/OnlyKey_Installer.bat

**Comment by onlykey** [comment]
@freeload101 Thanks! I know we have had users needing to use the app without admin privileges. I will test this out and see if we can add to our documentation.

**Comment by freeload101** [comment]
> @freeload101 Thanks! I know we have had users needing to use the app without admin privileges. I will test this out and see if we can add to our documentation.

Yah my Support form user "RMcCurdyDOTcom" has a reply to se issue but of course my account got "temporarily placed on hold as a precautionary measure." ...

feel free to take the script and use it or just make your binary package use MSI or NSIS something that has a extract flag...no need to "install" anything

**Comment by freeload101** [comment]
BUMP ? I am having issues with my DUO #2 softkey not working at all anymore :( I can't see to find where to get warranty or support...and I can't ask on the onlykey.discourse.group because BOTH my accounts I created to help you guys are locked ...

**Comment by onlykey** [comment]
@freeload101 Sorry about that, I found your username on the forum that you posted above and reenabled your account. I am not sure why it was blocked.

**Comment by freeload101** [comment]
Thank you! I tried to find a way to extract LZMA or whatever without 7z dll but as far as I can tell no way to extract the files ..I may check %TEMP% on install will see

**Comment by onlykey** [comment]
@freeload101 Thanks, I was going to see if there was another option when creating the package that doesn't use LZMA so standard ZIP utility could decompress.

**Comment by freeload101** [comment]
Thank you! 

You can just use powershell there is Expand-Archive way and a much faster way with calling  System.IO.Compression.ZipFile. I had to use it to make Bloodhound extract much faster (lots of tiny files)

https://github.com/freeload101/Bloodhound-Portable/blob/128f174015091db2a9e99ce4a8b3d74e2855dc88/BloodHound_Portable.bat#L103

**Comment by onlykey** [comment]
@freeload101 We can package the app using zlib instead of lzma. But the Expand-Archive method fails, are you able to unzip this one without needing 7zip?

**Comment by freeload101** [comment]
W00T! Thanks! Not sure it's kosher for Choco installer but I seen them use autohotkey so ill submit it and see what happens lol
 
 https://github.com/freeload101/SCRIPTS/blob/master/Windows_Powershell_ps/OnlyKey_Installer.ps1
