### ISSUE TITLE
pre-release 5.5.0 has outdated version and version_name referencing 5.3.6 from previous release

### ISSUE THREAD

**Issue by nkichukov** [trustcrypto/OnlyKey-App#209]
Hi, 

When building the latest pre-release the package ends up being created as OnlyKey_5.3.6_amd64.deb instead of OnlyKey_5.5.0_amd64.deb because the version and version_name in package.json(possibly others) have not been updated. Can you please fix this?

**Comment by rodgolpe** [comment]
Thanks for trying it out! The branch which included all the 5.5.0 updates (including its package.json) had not been merged. It's all up-to-date now.

**Comment by nkichukov** [comment]
Unfortunately the pre-release assets still contain outdated versions, can you ask github to rebuild those from the updated tag/commit? Thanks.
