### ISSUE TITLE
App does not prompt to unlock after timeout reached

### ISSUE THREAD

**Issue by jaroszke** [trustcrypto/OnlyKey-App#40]
The app does not request to unlock the OK once the set timeout is reached.

**Comment by jaroszke** [comment]
Setting a slot label for example after the timeout doesn't return label. But once OK is unlocked again that label is wrote and returned to the app. 
![aftertimeoutlabelset](https://cloud.githubusercontent.com/assets/9595840/18605177/cfc4248a-7c58-11e6-9e22-21388e56c33c.PNG)

**Comment by lupa18** [comment]
Same here
