### ISSUE TITLE
Error Loading Existing GPG Subkeys to OnlyKey

### ISSUE THREAD

**Issue by frankyyyyyyy** [trustcrypto/OnlyKey-App#82]
I am attempting to load existing encryption and signing subkeys to the OnlyKey via the RSA tab.  I import the backups to the keyring and have expected access to them.  I export the specific subkeys with gpg --armor --output <out_filename> --export-secret-keys <subkey_id>! (note the ! to specify the subkey id for export)

I put the OnlyKey into config mode and copy/paste the subkey block to the Windows app along with the complex password.

The app displays the following error:

Error parsing RSA key: Error: Invalid enum value.

Any insight is appreciated.

**Comment by onlykey** [comment]
@frankvirgato Just do -
gpg2 --export-secret-key -a "John Smith" > private.key

Also keep in mind that the key must be OpenPGP compatible. Here is the documentation for loading your own key - https://docs.crp.to/usersguide.html#loading-keys-a

**Comment by frankvirgato** [comment]
Hi

Thanks for the response.
I might be wrong, but doesn't that export the master key? If so, isn't the goal of the subkey to keep the master key off disk and confidential?
Would that work with the master private key not available?

Thanks!!

**Comment by onlykey** [comment]
@frankvirgato Depending on how your key is configured it may use the master (primary) key for signing messages or it may use a subkey. The default is usually to use the primary key for signing messages so if you want to use your OnlyKey to sign messages you would load this. If you don't have the primary key stored on your system then it would not be exported with the command provided as it is not present. If you do have the primary key stored on your system and are using a subkey for signing messages then you can still export the whole key but would just load the subkeys onto OnlyKey.

**Comment by frankvirgato** [comment]
Thanks for the response.
I resolved my issue by importing my master secret key, and noticed the app detected my 3 subkeys, for Sign, Encryption and Authentication, and asks which subkey you want to use.
I was previously trying to import the subkey secret key directly which resulted in the errors seen.

Thanks

Frank Virgato
Principal Consultant | Sentaris Pty Ltd
M: +61 401 148 815
E:   frank.virgato@sentaris.com.au<mailto:frank.virgato@sentaris.com.au>
W: www.sentaris.com.au<http://www.sentaris.com.au>

[cid:image001.jpg@01D2C578.0DC298D0]

**Comment by timetoseek** [comment]
We are only using 8,192 but key size for our OpenPGP emails.  But I can't seem to get this to work on OnlyKey.  
Please advise if anyone has had any luck using 8,192 bit size keys with OnlyKey?

Thank you.
