### ISSUE TITLE
Cannot initialize key select form due to invalid keys object

### ISSUE THREAD

**Issue by UniversalSuperBox** [trustcrypto/OnlyKey-App#83]
I've generated a new 2048-bit RSA key for the sole purpose of backing up my OnlyKey. I've exported it using the `gpg2 --export-secret-key -a "Backup Key"` command. After copying the entire armored block into the RSA Private Key field in the Keys menu, entering my passphrase, checking "Set as Backup Key", and clicking "Save to OnlyKey", the app returns the message `Cannot initialize key select form due to invalid keys object`.

This isn't a case of an incorrect passphrase. If I enter the incorrect passphrase on purpose, I get the correct error `Error parsing RSA key: Error: Private Key decryption failed. Did you forget your passcode?`

I also don't have an incorrectly formatted key, as I get a (slightly less helpful) `TypeError: Cannot read property 'decrypt' of undefined` when I break the key's formatting.

The key has firmware v0.2-beta.6c on it and I'm running Chrome 66.0.3359.139 on Solus.

**Comment by onlykey** [comment]
@UniversalSuperBox It looks like the key you are trying to use may not be OpenPGP compatible. The app uses OpenPGP.js for parsing keys.

**Comment by UniversalSuperBox** [comment]
That's interesting. How would I know if it was compatible or not? And how would I use GPG to generate an OpenPGP-compatible key?
