### ISSUE TITLE
Too hard to find

### ISSUE THREAD

**Issue by M-Pixel** [trustcrypto/OnlyKey-App#85]
It took me a while to figure out where to download the desktop client, now that the Chrome app has been removed from the store. There is no click-through from [crp.to](https://crp.to) to the actual installer. Check out your competitors' websites for examples of what your customers need and expect - see how easy it is to find an installer for YubiKey software, for example.

**Comment by onlykey** [comment]
crp.to is the site for CryptoTrust, there isn't much info about OnlyKey on the crp.to site because CryptoTrust is primarily a consulting company. The site for OnlyKey is onlykey.io. All documentation including the OnlyKey user's guide is on docs.crp.to. 

![image](https://user-images.githubusercontent.com/18121756/41246518-527cda30-6d79-11e8-9f16-bacf858f1c91.png)


The Chrome app is still available its just no longer searchable as Chrome has discontinued Chrome apps for everything but Chromebook.

**Comment by M-Pixel** [comment]
`crp.to` is the URL printed on the physical device that you ship out.  Your customers use and think about your product a small fraction of the day, not 24/7 like you.  This makes it difficult to relate, I understand, but trust me that very few of your customers have memorized the fact that https://onlykey.io even exists.

Even a Google search for "OnlyKey download" has your homepage as the first result, and even OnlyKey.io is several clicks and a lot of thinking away from the download.

Here's a typical user experience:

1. I'm at work for the first time since getting this OnlyKey.  I need to add a new password to it.  I don't have the software installed on this computer yet.  I don't remember exactly where I got it before, and I don't have the instruction paper that came with the device anymore.  Well, it says "crp.to" on it, so I'll go to that URL.
2. Look for "download", "install", "OnlyKey"... nothing.  Well, maybe OnlyKey is under "Products" - _click Products_
3. That jumped me straight to the OnlyKey website.  Looking for "download", "install", etc.  Nothing.  "Get Started" pages often contain downloads, so I'll try "Get Started".
4. This Get Started page shows me a newsletter signup (I already did that), a link to documentation (I already know how to use it), and an offer to send feedback through Twitter (obviously not the right course of action).  This must have been the wrong place to go, because I've never had a download link buried this deep before.  Let's go back.
5. The homepage has a "Support" link.  That's a common place for downloads, too, remembering my experience with ASUS motherboards etc.  Let's try that.
6. This support page definitely doesn't have any download links.  I give up on this website, I'll just search for it.
7. Being privacy-minded, I searched "onlykey app download" on Duck Duck Go.  The first result says "The OnlyKey App" - that's exactly what I'm looking for!  Click that.
8. This GitHub website has a lot of information all at once.  Where's my download button?  This is definitely about the OnlyKey app.  Aha, after reading a few paragraphs of information, I've finally come across "Obtain an installer from https://github.com/trustcrypto/OnlyKey-Chrome-App/releases/latest".

Reasonable, right?  And very easy to fix.

nvidia.com - "Drivers" is top-and-center.  Click on it and the next page has a big green download button.

raspberrypi.org - Second link in the navigation bar is "Downloads", leads to a page with downloads for numerous platforms.

**Comment by timetoseek** [comment]
A simple solution is to change "ONLYKEY" to www.ONLYKEY.io
And  please remove "crp.to" (if consulting services are to be offered, then maybe best to add a link/page to onlykey.io)  How about something like this:
![Suggestion for onlykey device labels](https://user-images.githubusercontent.com/26972658/57641373-b9290580-7569-11e9-9906-9f5937ea0c54.jpg "Suggestion for onlykey device labels")
sorry for my lack of creativity :slightly_frowning_face:  this is the best I can do, given my two left thumbs :point_right: :point_right:

**Comment by timetoseek** [comment]
This topic has some overlap with the Enterprise enhancement thread, so adding a link to it:
https://github.com/trustcrypto/OnlyKey-Firmware/issues/76

**Comment by M-Pixel** [comment]
Changing the URL helps.  There's still more than 2 clicks from onlykey.io to get the file, though, and I believe many would back out of "getting started" rather than clicking through to the documentation and then eventually finding the download link in there.
