### ISSUE TITLE
App Does Not Connect to Key After Fresh Firmware Install

### ISSUE THREAD

**Issue by josh-palan** [trustcrypto/OnlyKey-App#88]
After loading the Beta 7 firmware by following this guide:

https://docs.crp.to/upgradeguide.html

my OnlyKey is no longer recognized in the OnlyKey Desktop App. It recognizes that the key is plugged in, but it is stuck on Working... Please Wait, and never gives me the chance to setup the key. My key is bricked at this point. Any help is greatly appreciated.

**Comment by josh-palan** [comment]
More info:

```
user@pc:~uname -a
Linux user 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

OnlyKey Desktop App v5.1-beta.0

I tried loading both OnlyKey Color Standard Edition firmware and OnlyKey Color International Travel Edition firmware, neither worked.

**Comment by onlykey** [comment]
@josh-palan You have to load the new udev rules as the device VID/PID has changed:

"Note: Linux users must follow the following instructions to update the UDEV rule for the app to be able to communicate with the OnlyKey - [Linux Guide](https://docs.crp.to/linux.html)"

**Comment by josh-palan** [comment]
That fixes it! I totally missed that note. Thank you!
