### ISSUE TITLE
"auto-launch on login" can not be disabled

### ISSUE THREAD

**Issue by donestefan** [trustcrypto/OnlyKey-App#90]
The onlykey desktop app launches automatically on login. Even if the autostart option is disabled.
Tested on Win10_64bit.

**Comment by onlykey** [comment]
Sounds like this is related to https://github.com/trustcrypto/OnlyKey-App/issues/89
@rodgolpe

**Comment by donestefan** [comment]
Thanks for pointing me to #89 . I don't know why I missed this.
After playing around with the "auto-launch" setting in the app (switching it on/off repeatedly while watching for changes in the registry key `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`) it just started working after a while...

By the way, what is the `--hidden` supposed to do? If it is about starting the app minimized to the tray, then it is not working for me. The app always starts in foreground.

**Comment by rodgolpe** [comment]
Auto-launch seems to be erratic at the moment -- not starting hidden or not respecting the auto-launch setting in the app at all. It should be better in the next release.

**Comment by tafli** [comment]
Same here with Linux an app version 5.2. Any updates on this?

**Comment by onlykey** [comment]
@tafli The issue here was with Windows which was resolved in app version 5.2, for all OSes the app autostarts by default and you select for it not to autostart under Settings - Auto Launch App on System Login
