### ISSUE TITLE
unlocking onlykey for U2F on Firefox

### ISSUE THREAD

**Issue by donestefan** [trustcrypto/OnlyKey-App#91]
Hi,
I'm using onlykey as U2F Token for github. It is plain U2F - no Username/Password/... is stored on onlykey.
When entering the github password before unlocking onlykey, then U2F does not work.
When unlocking onlykey before entering the password, then U2F works as expected.
I'm having the same issue on other u2f protected sites like google.

I'm using Firefox 65 on win10_64. I have not tested chrome.

**Comment by onlykey** [comment]
@donestefan Do you get any error from github like no security key found? If device is locked it will not work for 2FA until PIN is entered.

**Comment by rodgolpe** [comment]
Yeah, I have to say this is interesting, but not sure what we can do about it beyond "thank you for reporting the correct way to use it."

I'll leave this issue open in case anyone can offer a software solution.

**Comment by donestefan** [comment]
@onlykey: 
No, I don't see an error message. I't just doesn't work. Github is asking me to insert my security key and waits. I insert the key, enter the pin and then I trigger the U2F Slot. But github is still waiting for a security key to be inserted...

After 30 Seconds I see this message. But its just a general timeout when 2FA has not succeeded within 30s.
![grafik](https://user-images.githubusercontent.com/8457107/53240070-ef0eca00-369d-11e9-92d3-20b13d171007.png)

I have to refresh the page and now I can immediately trigger the U2F Slot (since the PIN has been entered before and onlykey is still unlocked). This time U2F works.

**Comment by donestefan** [comment]
I tested chrome portable, and it behaves a little different.
Github is asking me to insert my security key and waits. I insert the onlykey and get this error message (even before entering the PIN). 
![grafik](https://user-images.githubusercontent.com/8457107/53242592-7c095180-36a5-11e9-8792-1debb9f0219a.png)
The error seems to be triggered by a locked onlykey being plugged in - long before the regular 30s timeout happens. 

I ignore the error, unlock onlykey, refresh the page and then trigger the U2F Slot (in this particular order) to log in successfully.

Is anyone else seeing the same behavior, or is it just me?

**Comment by onlykey** [comment]
@donestefan If the key is locked this is expected. It would need to be unlocked before loading the page.
