### ISSUE TITLE
OnlyKey with Fedora 29

### ISSUE THREAD

**Issue by clue404** [trustcrypto/OnlyKey-App#94]
Hello,

is it possible to install the OnlyKey App in Fedora 29 without using the Chrome App? I really don't want to use Chrome.

Thanks

**Comment by onlykey** [comment]
I believe there is a support forum topic about this https://forum.onlykey.io

You need a way to convert to RPM - https://www.systutorials.com/241054/how-to-install-deb-packages-on-fedora/

**Comment by clue404** [comment]
Thanks

**Comment by onlykey** [comment]
@clue404 Can you share what solution worked for you?

**Comment by clue404** [comment]
I don't run Fedora anymore :') but I think I used alien to convert deb to rpm
