### ISSUE TITLE
Swap slots

### ISSUE THREAD

**Issue by toastal** [trustcrypto/OnlyKey-App#96]
Currently you can't move a slots data to a different slot (e.g. moving 1a to 1b). The slots are currently stuck in their places, but I want to reorganize now that I have more accounts. To do this now you will need all of your information for the slot to reconstruct it when it should be simpler to move.

**Comment by haplo** [comment]
Slots seem to be write-only, so they are not editable. I wonder if we would need a "swap slots" operation at the firmware level, so the desktop and CLI apps can just issue a "swap slot N with slot M" operation, and the OnlyKey would execute it.
