### ISSUE TITLE
I can't connect the app to my OnlyKey device. It keeps saying "Working... Please wait".

### ISSUE THREAD

**Issue by xCapRx** [trustcrypto/OnlyKey-App#97]
I'm having the same issue as was posted [here before](https://github.com/trustcrypto/OnlyKey-App/issues/30) and I'm running Linux Mint. I created a MX Linux VM to see if I could get around the issue but no dice. Tried following the linked instructions but didn't get anywhere since I couldn't find the "49-teensy.rules" file.

I have to ask why the YubiKey apps work on Linux but the OnlyKey app doesn't? Can't OnlyKey fix this bug in their software? 

It seems to me like OnlyKey didn't do much testing on Linux before releasing their product. If they had, maybe this issue wouldn't exist. Sure Linux is a nitch group being something like 2% of the entire desktop PC market but people who take security seriously tend to use Linux more often than Mac or Windows and would be the customer type that would purchase an OnlyKey device.

**Comment by onlykey** [comment]
@xCapRx Its pretty standard to have to add a udev rule to access a USB device in Linux, this is in the instructions in the user's guide - https://docs.crp.to/linux.html

**Comment by xCapRx** [comment]
That worked! Thanks. I still don't understand why the Yubico apps work without hassle on Linux though. 

That said however,  I just want to say your product clearly looks far superior to what Yubico has now that I've had a tour of your app.  On top of having 12 slots instead of 2 on a Yubikey, there are a lot more options to customize each slot, a lockout timer, self-destruct PIN, backup option, PGP support,  and the whole things is open source to top if off. I'm not an expert but for whatever it's worth, I think I can confidently say you guys did a tremendous job! Thanks for making a great product. I look forward to using it :)
